INSERT INTO t_p31606708_tech_buying_service.catalog (category, brand, model, color, storage, ram, region, availability, price, has_photo) VALUES
-- AirPods
('AirPods','Apple','EarPods Type-C',NULL,NULL,NULL,NULL,'in_stock',1900,true),
('AirPods','Apple','EarPods Lightning',NULL,NULL,NULL,NULL,'on_order',1800,true),
('AirPods','Apple','AirPods 4',NULL,NULL,NULL,'US','in_stock',9400,true),
('AirPods','Apple','AirPods 4 ANC',NULL,NULL,NULL,'US','in_stock',11900,true),
('AirPods','Apple','AirPods Pro 2 Type-C',NULL,NULL,NULL,'US','in_stock',15100,true),
('AirPods','Apple','AirPods Pro 3',NULL,NULL,NULL,'US','in_stock',18400,true),
('AirPods','Apple','AirPods Max 2','Midnight',NULL,NULL,'US','on_order',40500,true),
('AirPods','Apple','AirPods Max 2','Starlight',NULL,NULL,'US','on_order',44400,true),
('AirPods','Apple','AirPods Max 2','Purple',NULL,NULL,'US','on_order',41800,true),
('AirPods','Apple','AirPods Max 2','Blue',NULL,NULL,'US','on_order',44400,true),
-- Apple Watch
('Apple Watch','Apple','Watch SE3 40mm','Midnight',NULL,NULL,'US','in_stock',20400,false),
('Apple Watch','Apple','Watch SE3 40mm','Starlight',NULL,NULL,'US','in_stock',21200,false),
('Apple Watch','Apple','Watch SE3 44mm','Midnight',NULL,NULL,'US','in_stock',23200,false),
('Apple Watch','Apple','Watch SE3 44mm','Starlight',NULL,NULL,'US','in_stock',23300,false),
('Apple Watch','Apple','Watch S11 42mm','Jet Black',NULL,NULL,'US','in_stock',26900,true),
('Apple Watch','Apple','Watch S11 42mm','Rose Gold',NULL,NULL,'US','in_stock',26800,true),
('Apple Watch','Apple','Watch S11 42mm','Silver',NULL,NULL,'US','in_stock',28700,true),
('Apple Watch','Apple','Watch S11 46mm','Jet Black',NULL,NULL,'US','in_stock',30000,true),
('Apple Watch','Apple','Watch S11 46mm','Rose Gold',NULL,NULL,'US','in_stock',29400,true),
('Apple Watch','Apple','Watch S11 46mm','Space Gray',NULL,NULL,'US','in_stock',28900,true),
('Apple Watch','Apple','Watch S11 46mm','Silver',NULL,NULL,'US','in_stock',29400,true),
('Apple Watch','Apple','Watch Ultra 2 49mm','Black Ti',NULL,NULL,'US','on_order',56100,true),
('Apple Watch','Apple','Watch Ultra 3 49mm','Natural Ti',NULL,NULL,'US','on_order',63700,false),
-- iPad
('Apple iPad','Apple','iPad 11 128GB Silver Wi-Fi',NULL,'128GB',NULL,'US','in_stock',30800,true),
('Apple iPad','Apple','iPad 11 128GB Blue Wi-Fi',NULL,'128GB',NULL,'US','in_stock',29400,true),
('Apple iPad','Apple','iPad 11 256GB Silver Wi-Fi',NULL,'256GB',NULL,'US','in_stock',39500,true),
('Apple iPad','Apple','iPad Air 11 M4 128GB Blue Wi-Fi',NULL,'128GB',NULL,'US','on_order',50600,false),
('Apple iPad','Apple','iPad Air 11 M4 256GB Blue Wi-Fi',NULL,'256GB',NULL,'US','on_order',59800,false),
('Apple iPad','Apple','iPad Air 13 M4 128GB Blue Wi-Fi',NULL,'128GB',NULL,'US','on_order',69300,false),
('Apple iPad','Apple','iPad Mini 7 128GB Starlight Wi-Fi',NULL,'128GB',NULL,'US','on_order',37900,true),
('Apple iPad','Apple','Apple Pencil Pro',NULL,NULL,NULL,'US','in_stock',8900,true),
-- Samsung S
('Samsung S-Z','Samsung','Galaxy S25','Navy','256GB','12GB','EU','in_stock',53400,true),
('Samsung S-Z','Samsung','Galaxy S25','Silver','256GB','12GB','EU','in_stock',52000,true),
('Samsung S-Z','Samsung','Galaxy S25 Ultra','Black','256GB','12GB','EU','in_stock',71900,true),
('Samsung S-Z','Samsung','Galaxy S25 Ultra','Black','512GB','12GB','EU','in_stock',80000,true),
('Samsung S-Z','Samsung','Galaxy S25 Ultra','Gray','512GB','12GB','EU','in_stock',80000,true),
('Samsung S-Z','Samsung','Galaxy S26 Ultra','Black','256GB','12GB','EU','in_stock',85400,false),
('Samsung S-Z','Samsung','Galaxy S26','Black','256GB','12GB','EU','on_order',60800,false),
('Samsung S-Z','Samsung','Galaxy S26','Blue','256GB','12GB','EU','on_order',60600,false);
