ALTER TABLE tools_products
  ADD COLUMN IF NOT EXISTS base_price NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS my_price NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS amount TEXT DEFAULT '';
