UPDATE t_p31606708_tech_buying_service.catalog SET description='Samsung Galaxy S25 Ultra с встроенным S Pen, камерой 200 Мп и Snapdragon 8 Elite. Galaxy AI.', specs='{"Процессор":"Snapdragon 8 Elite","ОЗУ":"12 ГБ","Экран":"6.9 QHD+ AMOLED 120Гц","Камера":"200+50+10 Мп","S Pen":"встроен","5G":"да","Батарея":"5000 мАч"}' WHERE category='Samsung S-Z' AND model ILIKE '%S25 Ultra%';
UPDATE t_p31606708_tech_buying_service.catalog SET description='Samsung Galaxy S25+ — флагман с Snapdragon 8 Elite, Galaxy AI и экраном 6.7.', specs='{"Процессор":"Snapdragon 8 Elite","ОЗУ":"12 ГБ","Экран":"6.7 FHD+ AMOLED 120Гц","Камера":"50+10+12 Мп","5G":"да","Батарея":"4900 мАч"}' WHERE category='Samsung S-Z' AND (model ILIKE '%S25+%' OR model ILIKE '%S25 Plus%');
UPDATE t_p31606708_tech_buying_service.catalog SET description='Samsung Galaxy S25 — компактный флагман с Galaxy AI и Snapdragon 8 Elite.', specs='{"Процессор":"Snapdragon 8 Elite","ОЗУ":"12 ГБ","Экран":"6.2 FHD+ AMOLED 120Гц","Камера":"50+12+10 Мп","5G":"да","Батарея":"4000 мАч"}' WHERE category='Samsung S-Z' AND model ILIKE '%S25%' AND model NOT ILIKE '%Ultra%' AND model NOT ILIKE '%+%' AND model NOT ILIKE '%Plus%';
UPDATE t_p31606708_tech_buying_service.catalog SET description='Samsung Galaxy A55 — AMOLED 120Гц, защита IP67 и тройная камера 50 Мп. Долгая поддержка.', specs='{"Процессор":"Exynos 1480","ОЗУ":"8 ГБ","Экран":"6.6 AMOLED 120Гц","Камера":"50+12+5 Мп","IP67":"да","5G":"да","Батарея":"5000 мАч"}' WHERE category='Samsung A-M' AND model ILIKE '%A55%';
UPDATE t_p31606708_tech_buying_service.catalog SET description='Samsung Galaxy A35 — AMOLED-дисплей, IP67 и камера 50 Мп. Надёжный выбор в среднем сегменте.', specs='{"Процессор":"Exynos 1380","ОЗУ":"6 ГБ","Экран":"6.6 AMOLED 120Гц","Камера":"50+8+5 Мп","IP67":"да","5G":"да","Батарея":"5000 мАч"}' WHERE category='Samsung A-M' AND model ILIKE '%A35%';
UPDATE t_p31606708_tech_buying_service.catalog SET description='iPad 11 с A16 Bionic, дисплеем Liquid Retina 11 и поддержкой Apple Pencil Pro.', specs='{"Чип":"Apple A16 Bionic","Дисплей":"11 Liquid Retina","Разъём":"USB-C","Apple Pencil":"Pro","Wi-Fi":"6E"}' WHERE category='Apple iPad' AND model ILIKE '%iPad 11%';
UPDATE t_p31606708_tech_buying_service.catalog SET description='iPad Air M4 — тонкий и мощный планшет. Чип M4, поддержка Apple Pencil Pro и Magic Keyboard.', specs='{"Чип":"Apple M4","Дисплей":"11 или 13 Liquid Retina","Apple Pencil":"Pro","Wi-Fi":"6E","Magic Keyboard":"да"}' WHERE category='Apple iPad' AND model ILIKE '%Air%';
UPDATE t_p31606708_tech_buying_service.catalog SET description='iPad Mini 7 с A17 Pro — компактный iPad. Вмещается в карман, поддерживает Apple Pencil Pro.', specs='{"Чип":"Apple A17 Pro","Дисплей":"8.3 Liquid Retina","Apple Pencil":"Pro","Wi-Fi":"6E","Разъём":"USB-C"}' WHERE category='Apple iPad' AND model ILIKE '%Mini%';
UPDATE t_p31606708_tech_buying_service.catalog SET description='Apple Pencil Pro — стилус с нажатием, вращением и поддержкой Squeeze.', specs='{"Совместимость":"iPad Air M2+, iPad Pro M4+, iPad Mini 7, iPad 11+","Зарядка":"MagSafe","Особенности":"Squeeze, Rotation, Find My"}' WHERE category='Apple iPad' AND model ILIKE '%Pencil%';
