INSERT INTO t_p31606708_tech_buying_service.catalog (category, brand, model, color, storage, ram, region, availability, price, has_photo) VALUES
-- Realme
('Realme / OnePlus / Nothing','Realme','Realme C71','Green','256GB','8GB','RU','on_order',10000,FALSE),
('Realme / OnePlus / Nothing','Realme','Realme C71','White','256GB','8GB','RU','on_order',10000,FALSE),
('Realme / OnePlus / Nothing','Realme','Realme C75','Black','128GB','8GB','RU','on_order',10000,FALSE),
('Realme / OnePlus / Nothing','Realme','Realme C85 Pro','Purple','256GB','8GB','RU','on_order',15200,FALSE),
-- OnePlus
('Realme / OnePlus / Nothing','OnePlus','OnePlus 13','Midnight','256GB','12GB','EU','on_order',54000,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus 13R','Noir','256GB','12GB','EU','on_order',29600,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus 13R','Trail','256GB','12GB','EU','on_order',29600,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus 13S','Black','256GB','12GB','EU','on_order',40200,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus 13S','Green','256GB','12GB','EU','on_order',40200,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus 13S','Black','512GB','12GB','EU','on_order',42100,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus 13S','Green','512GB','12GB','EU','on_order',42100,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus 15','Violet','512GB','16GB','EU','on_order',65700,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus 15','Black','512GB','16GB',NULL,'in_stock',NULL,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus 15','Sand','512GB','16GB',NULL,'in_stock',NULL,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus 15','Black','1TB','16GB','CN','on_order',67600,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus 15R','Mint','256GB','12GB','EU','on_order',40200,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus 15R','Mint','512GB','12GB','EU','on_order',41000,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus 15R','Black','512GB','12GB','EU','on_order',41000,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus Buds 4','Gray',NULL,NULL,'EU','on_order',5700,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus Buds 4','Green',NULL,NULL,'EU','on_order',5700,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus Buds Pro 3','Blue',NULL,NULL,'EU','on_order',9300,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus Buds Pro 3','Lunar',NULL,NULL,'EU','on_order',9300,FALSE),
('Realme / OnePlus / Nothing','OnePlus','OnePlus Buds Pro 3','Midnight',NULL,NULL,'EU','on_order',9300,FALSE),
-- Nothing
('Realme / OnePlus / Nothing','Nothing','Nothing Phone 3A Pro','Black','256GB','12GB','EU','on_order',30400,FALSE),
('Realme / OnePlus / Nothing','Nothing','Nothing Phone 4A','Black','256GB','12GB','EU','on_order',39400,FALSE),
('Realme / OnePlus / Nothing','Nothing','Nothing Phone 4A','Black','256GB','8GB','EU','on_order',37000,FALSE),

-- Sony PS5
('Sony / XBOX / GoPro','Sony','PS VR2',NULL,NULL,NULL,'US','on_order',33700,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 Disc Drive',NULL,NULL,NULL,'US','in_stock',8800,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 DualSense Camouflage',NULL,NULL,NULL,'US','in_stock',5600,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 DualSense Chroma Pearl',NULL,NULL,NULL,NULL,'in_stock',NULL,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 DualSense Cosmic Red',NULL,NULL,NULL,'US','in_stock',5300,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 DualSense Galactic Purple',NULL,NULL,NULL,'US','in_stock',5300,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 DualSense Midnight Black',NULL,NULL,NULL,'US','in_stock',5600,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 DualSense Starlight Blue',NULL,NULL,NULL,'US','in_stock',5300,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 DualSense Sterling Silver',NULL,NULL,NULL,'US','in_stock',5700,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 DualSense Nova Pink',NULL,NULL,NULL,'US','in_stock',6400,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 DualSense Cobalt Blue',NULL,NULL,NULL,'US','in_stock',5300,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 DualSense Edge Midnight Black',NULL,NULL,NULL,'US','on_order',16600,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 DualSense Edge White',NULL,NULL,NULL,'US','on_order',16600,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 DualSense Volcanic Red',NULL,NULL,NULL,'US','in_stock',5300,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 DualSense White',NULL,NULL,NULL,'US','on_order',5600,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 Pro 2TB Digital Edition',NULL,'2TB',NULL,'US','in_stock',75100,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 Slim Digital Edition',NULL,'1TB',NULL,'US','on_order',42700,TRUE),
('Sony / XBOX / GoPro','Sony','PS5 Slim Digital Edition',NULL,'825GB',NULL,'US','in_stock',41700,FALSE),
('Sony / XBOX / GoPro','Sony','PS5 Slim Disc Edition',NULL,'1TB',NULL,'US','in_stock',46900,FALSE),
-- Steam/Nintendo
('Sony / XBOX / GoPro','Valve','Steam Deck OLED','Black','512GB',NULL,'US','on_order',57600,FALSE),
('Sony / XBOX / GoPro','Valve','Steam Deck OLED','Black','1TB',NULL,'US','on_order',67600,FALSE),
('Sony / XBOX / GoPro','Nintendo','Nintendo Switch 2',NULL,NULL,NULL,'US','on_order',39400,FALSE),
('Sony / XBOX / GoPro','Nintendo','Nintendo Switch 2 Mario Kart World Bundle',NULL,NULL,NULL,'US','on_order',42200,FALSE),
-- GoPro / DJI / Insta360 / Instax
('Sony / XBOX / GoPro','GoPro','GoPro HERO 12',NULL,NULL,NULL,NULL,'in_stock',NULL,FALSE),
('Sony / XBOX / GoPro','GoPro','GoPro HERO 13',NULL,NULL,NULL,'US','on_order',24500,FALSE),
('Sony / XBOX / GoPro','GoPro','GoPro HERO 4K',NULL,NULL,NULL,'US','on_order',15500,FALSE),
('Sony / XBOX / GoPro','Insta360','Insta 360 X3',NULL,NULL,NULL,'US','on_order',23900,FALSE),
('Sony / XBOX / GoPro','Insta360','Insta 360 X5',NULL,NULL,NULL,'US','on_order',35100,FALSE),
('Sony / XBOX / GoPro','Fujifilm','Instax Mini 12','Green',NULL,NULL,'US','on_order',8300,FALSE),
('Sony / XBOX / GoPro','Fujifilm','Instax Mini 12','Blue',NULL,NULL,'US','on_order',7800,FALSE),
('Sony / XBOX / GoPro','Fujifilm','Instax Mini 12','Purple',NULL,NULL,'US','on_order',8300,FALSE),
('Sony / XBOX / GoPro','Fujifilm','Instax Mini 12','White',NULL,NULL,'US','on_order',8300,FALSE),
('Sony / XBOX / GoPro','DJI','DJI Osmo Pocket 3 Creator Combo',NULL,NULL,NULL,'US','on_order',40400,FALSE),

-- Яндекс Станции
('Яндекс / JBL / Marshall','Яндекс','Станция Лайт 2','Фиолетовый',NULL,NULL,NULL,'on_order',4500,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Лайт 2','Синий',NULL,NULL,NULL,'in_stock',4500,TRUE),
('Яндекс / JBL / Marshall','Яндекс','Станция Лайт 2','Зелёный',NULL,NULL,NULL,'in_stock',4500,TRUE),
('Яндекс / JBL / Marshall','Яндекс','Станция Лайт 2','Коралловый',NULL,NULL,NULL,'in_stock',4500,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Лайт 2','Розовый',NULL,NULL,NULL,'in_stock',NULL,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Мини 3','Бирюзовый',NULL,NULL,NULL,'on_order',6600,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Мини 3','Лиловый',NULL,NULL,NULL,'on_order',6600,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Мини 3','Серый',NULL,NULL,NULL,'on_order',6600,TRUE),
('Яндекс / JBL / Marshall','Яндекс','Станция Мини 3','Чёрный',NULL,NULL,NULL,'on_order',6600,TRUE),
('Яндекс / JBL / Marshall','Яндекс','Станция Мини 3 Про','Зеленый',NULL,NULL,'RU','on_order',9500,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Мини 3 Про','Синий',NULL,NULL,'RU','on_order',9500,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Мини 3 Про','Серый',NULL,NULL,'RU','on_order',9500,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Мини 3 Про','Черный',NULL,NULL,'RU','on_order',9500,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Миди','Черный',NULL,NULL,NULL,'in_stock',NULL,TRUE),
('Яндекс / JBL / Marshall','Яндекс','Станция Миди','Серый',NULL,NULL,'RU','in_stock',12100,TRUE),
('Яндекс / JBL / Marshall','Яндекс','Станция Миди','Изумрудный',NULL,NULL,'RU','in_stock',11700,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Миди','Оранжевый',NULL,NULL,'RU','in_stock',11700,TRUE),
('Яндекс / JBL / Marshall','Яндекс','Станция Миди','Малиновый',NULL,NULL,'RU','in_stock',12000,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Стрит','Черный',NULL,NULL,'RU','on_order',8000,TRUE),
('Яндекс / JBL / Marshall','Яндекс','Станция Стрит','Зеленый',NULL,NULL,'RU','on_order',8000,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Стрит','Оранжевый',NULL,NULL,'RU','on_order',8000,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Макс','Зелёный',NULL,NULL,NULL,'on_order',26800,TRUE),
('Яндекс / JBL / Marshall','Яндекс','Станция Макс','Чёрный',NULL,NULL,NULL,'on_order',26800,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Макс','Бежевый',NULL,NULL,'RU','on_order',26700,TRUE),
('Яндекс / JBL / Marshall','Яндекс','Станция Макс','Бирюзовый',NULL,NULL,'RU','on_order',26700,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Макс','Красный',NULL,NULL,NULL,'on_order',26800,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Дуо Макс','Красный',NULL,NULL,'RU','on_order',34200,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция Дуо Макс','Черный',NULL,NULL,NULL,'in_stock',NULL,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция 3','Фиолетовый',NULL,NULL,NULL,'in_stock',20100,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция 3','Серый',NULL,NULL,NULL,'on_order',20100,FALSE),
('Яндекс / JBL / Marshall','Яндекс','Станция 3','Чёрный',NULL,NULL,NULL,'in_stock',20100,FALSE),
-- JBL
('Яндекс / JBL / Marshall','JBL','JBL Clip 5','Black',NULL,NULL,'US','on_order',5000,FALSE),
('Яндекс / JBL / Marshall','JBL','JBL Charge 5','Gray',NULL,NULL,'US','on_order',8400,FALSE),
('Яндекс / JBL / Marshall','JBL','JBL Charge 5','Teal',NULL,NULL,'US','on_order',9400,FALSE),
('Яндекс / JBL / Marshall','JBL','JBL Charge 6','Blue',NULL,NULL,'US','on_order',9800,FALSE),
('Яндекс / JBL / Marshall','JBL','JBL Charge 6','Red',NULL,NULL,'US','on_order',9800,FALSE),
('Яндекс / JBL / Marshall','JBL','JBL Charge 6','Squad',NULL,NULL,'US','on_order',9800,FALSE),
('Яндекс / JBL / Marshall','JBL','JBL Clip 5','White',NULL,NULL,'US','on_order',5000,FALSE),
('Яндекс / JBL / Marshall','JBL','JBL Flip 7','White',NULL,NULL,'US','on_order',7500,FALSE),
('Яндекс / JBL / Marshall','JBL','JBL Go 4','Black',NULL,NULL,'US','on_order',3200,FALSE),
('Яндекс / JBL / Marshall','JBL','JBL Boombox 3','Camouflage',NULL,NULL,'US','on_order',26700,FALSE),
('Яндекс / JBL / Marshall','JBL','JBL Boombox 4','Black',NULL,NULL,'US','on_order',38900,FALSE),
('Яндекс / JBL / Marshall','JBL','JBL Boombox 4','Squad',NULL,NULL,'US','on_order',38400,FALSE),
('Яндекс / JBL / Marshall','JBL','JBL Boombox 4','White',NULL,NULL,'US','on_order',42700,FALSE),
('Яндекс / JBL / Marshall','JBL','JBL Partybox 1100 Ultimate',NULL,NULL,NULL,'US','on_order',96200,FALSE),
('Яндекс / JBL / Marshall','JBL','JBL Partybox 120',NULL,NULL,NULL,'US','on_order',28300,FALSE),
('Яндекс / JBL / Marshall','JBL','JBL Partybox 520',NULL,NULL,NULL,'US','on_order',52400,FALSE),
('Яндекс / JBL / Marshall','JBL','JBL Partybox 710',NULL,NULL,NULL,'US','on_order',55300,FALSE),
-- Marshall
('Яндекс / JBL / Marshall','Marshall','Marshall Major 5','Black',NULL,NULL,'US','on_order',5800,FALSE),
('Яндекс / JBL / Marshall','Marshall','Marshall Major 5','Brown',NULL,NULL,'US','on_order',5800,FALSE),
('Яндекс / JBL / Marshall','Marshall','Marshall Major 5','Blue',NULL,NULL,'US','on_order',5800,FALSE),
('Яндекс / JBL / Marshall','Marshall','Marshall Major 5','Cream',NULL,NULL,'US','on_order',5800,FALSE),
('Яндекс / JBL / Marshall','Marshall','Marshall Motif 2 ANC','Black',NULL,NULL,'US','on_order',12100,FALSE);
