INSERT INTO t_p31606708_tech_buying_service.catalog (category, brand, model, color, storage, ram, region, availability, price, has_photo) VALUES
-- Galaxy Buds
('Samsung A-M','Samsung','Galaxy Buds 3','White',NULL,NULL,'EU','in_stock',6900,TRUE),
('Samsung A-M','Samsung','Galaxy Buds 3','Silver',NULL,NULL,'EU','in_stock',6600,TRUE),
('Samsung A-M','Samsung','Galaxy Buds 3 Pro','White',NULL,NULL,NULL,'in_stock',NULL,TRUE),
('Samsung A-M','Samsung','Galaxy Buds 3 Pro','Silver',NULL,NULL,'EU','in_stock',10600,TRUE),
('Samsung A-M','Samsung','Galaxy Buds 3 FE','Black',NULL,NULL,'EU','on_order',6100,FALSE),
('Samsung A-M','Samsung','Galaxy Buds 3 FE','Gray',NULL,NULL,'EU','on_order',6100,FALSE),
('Samsung A-M','Samsung','Galaxy Buds 4','Black',NULL,NULL,'EU','on_order',5800,FALSE),
('Samsung A-M','Samsung','Galaxy Buds 4','White',NULL,NULL,'EU','on_order',11100,FALSE),
('Samsung A-M','Samsung','Galaxy Buds 4 Pro','Black',NULL,NULL,'EU','in_stock',14700,FALSE),
('Samsung A-M','Samsung','Galaxy Buds 4 Pro','White',NULL,NULL,'EU','in_stock',14600,FALSE),
-- Galaxy Watch
('Samsung A-M','Samsung','Galaxy Watch 7 44mm','Silver',NULL,NULL,NULL,'in_stock',NULL,TRUE),
('Samsung A-M','Samsung','Galaxy Watch 7 Ultra 47mm LTE','White',NULL,NULL,'EU','on_order',23100,FALSE),
('Samsung A-M','Samsung','Galaxy Watch 8 40mm LTE','Graphite',NULL,NULL,NULL,'in_stock',NULL,TRUE),
('Samsung A-M','Samsung','Galaxy Watch 8 40mm','Silver',NULL,NULL,'EU','on_order',17500,FALSE),
('Samsung A-M','Samsung','Galaxy Watch 8 40mm','Graphite',NULL,NULL,'EU','on_order',16200,FALSE),
('Samsung A-M','Samsung','Galaxy Watch 8 40mm LTE','Graphite',NULL,NULL,'EU','in_stock',18900,FALSE),
('Samsung A-M','Samsung','Galaxy Watch 8 44mm','Silver',NULL,NULL,'EU','in_stock',17400,FALSE),
('Samsung A-M','Samsung','Galaxy Watch 8 44mm LTE','Silver',NULL,NULL,'EU','on_order',17600,FALSE),
('Samsung A-M','Samsung','Galaxy Watch 8 44mm','Graphite',NULL,NULL,'EU','on_order',17400,FALSE),
('Samsung A-M','Samsung','Galaxy Watch 8 44mm LTE','Graphite',NULL,NULL,'EU','on_order',18700,FALSE),
('Samsung A-M','Samsung','Galaxy Watch 8 Ultra 47mm LTE','White',NULL,NULL,'EU','in_stock',25800,FALSE),
('Samsung A-M','Samsung','Galaxy Watch 8 Classic 46mm','Black',NULL,NULL,'EU','on_order',20200,FALSE),
('Samsung A-M','Samsung','Galaxy Watch 8 Classic 46mm','White',NULL,NULL,'EU','on_order',20200,FALSE),
('Samsung A-M','Samsung','Galaxy Watch 8 Classic 46mm LTE','White',NULL,NULL,'EU','on_order',21400,FALSE),
('Samsung A-M','Samsung','Galaxy Watch 8 Ultra 47mm LTE','Blue',NULL,NULL,'EU','on_order',26400,FALSE),
('Samsung A-M','Samsung','Galaxy Watch 8 Ultra 47mm LTE','Gray',NULL,NULL,'EU','on_order',26200,FALSE),
('Samsung A-M','Samsung','Galaxy Watch 8 Ultra 47mm LTE','Silver',NULL,NULL,'EU','on_order',27200,FALSE),
-- Galaxy Tab
('Samsung A-M','Samsung','Galaxy Tab A9','Graphite','64GB','4GB',NULL,'in_stock',NULL,FALSE),
-- Samsung A
('Samsung A-M','Samsung','Galaxy A07','Violet','64GB','4GB','EU','on_order',8100,FALSE),
('Samsung A-M','Samsung','Galaxy A07','Green','64GB','4GB','EU','on_order',8000,FALSE),
('Samsung A-M','Samsung','Galaxy A07','Violet','128GB','4GB','EU','in_stock',8900,TRUE),
('Samsung A-M','Samsung','Galaxy A07','Green','128GB','4GB','EU','on_order',8900,TRUE),
('Samsung A-M','Samsung','Galaxy A07','Black','128GB','6GB','EU','on_order',9900,TRUE),
('Samsung A-M','Samsung','Galaxy A16','Black','128GB','4GB','EU','on_order',9600,TRUE),
('Samsung A-M','Samsung','Galaxy A17','Gray','128GB','4GB','EU','in_stock',12200,TRUE),
('Samsung A-M','Samsung','Galaxy A17','Black','128GB','4GB',NULL,'in_stock',NULL,TRUE),
('Samsung A-M','Samsung','Galaxy A17','Blue','128GB','4GB','EU','in_stock',12100,TRUE),
('Samsung A-M','Samsung','Galaxy A17','Gray','256GB','8GB','EU','in_stock',14800,TRUE),
('Samsung A-M','Samsung','Galaxy A17','Black','256GB','8GB','EU','in_stock',14800,TRUE),
('Samsung A-M','Samsung','Galaxy A17','Blue','256GB','8GB','EU','in_stock',14800,TRUE),
('Samsung A-M','Samsung','Galaxy A26','White','128GB','6GB','EU','on_order',16000,TRUE),
('Samsung A-M','Samsung','Galaxy A26','Black','256GB','8GB','EU','on_order',18800,TRUE),
('Samsung A-M','Samsung','Galaxy A26','White','256GB','8GB','EU','on_order',18800,TRUE),
('Samsung A-M','Samsung','Galaxy A26','Pink','256GB','8GB','EU','on_order',18800,FALSE),
('Samsung A-M','Samsung','Galaxy A36','Lime','128GB','8GB','EU','on_order',20500,TRUE),
('Samsung A-M','Samsung','Galaxy A36','Black','256GB','8GB','EU','on_order',23100,TRUE),
('Samsung A-M','Samsung','Galaxy A36','Lime','256GB','8GB','EU','on_order',23000,TRUE),
('Samsung A-M','Samsung','Galaxy A36','White','256GB','8GB','EU','on_order',23100,TRUE),
('Samsung A-M','Samsung','Galaxy A36','Lime','256GB','12GB','EU','on_order',23900,TRUE),
('Samsung A-M','Samsung','Galaxy A37','White','128GB','8GB','EU','on_order',28800,FALSE),
('Samsung A-M','Samsung','Galaxy A56','Graphite','128GB','8GB','EU','in_stock',24900,TRUE),
('Samsung A-M','Samsung','Galaxy A56','Lightgray','128GB','8GB','EU','in_stock',25700,TRUE),
('Samsung A-M','Samsung','Galaxy A56','Pink','128GB','8GB',NULL,'in_stock',NULL,TRUE),
('Samsung A-M','Samsung','Galaxy A56','Graphite','256GB','8GB','EU','on_order',27700,TRUE),
('Samsung A-M','Samsung','Galaxy A56','Lightgray','256GB','8GB','EU','in_stock',27700,TRUE),
('Samsung A-M','Samsung','Galaxy A56','Olive','256GB','8GB','EU','in_stock',27700,TRUE),
('Samsung A-M','Samsung','Galaxy A56','Pink','256GB','8GB','EU','in_stock',27700,TRUE),
('Samsung A-M','Samsung','Galaxy A56','Graphite','256GB','12GB','EU','in_stock',29300,TRUE),
('Samsung A-M','Samsung','Galaxy A56','Lightgray','256GB','12GB','EU','in_stock',29300,TRUE),
('Samsung A-M','Samsung','Galaxy A56','Olive','256GB','12GB','EU','in_stock',28900,TRUE),
('Samsung A-M','Samsung','Galaxy A56','Pink','256GB','12GB','EU','in_stock',29300,TRUE),
('Samsung A-M','Samsung','Galaxy A57','Icyblue','128GB','8GB','EU','on_order',31500,FALSE),
('Samsung A-M','Samsung','Galaxy A57','Lilac','128GB','8GB','EU','on_order',31500,FALSE),
('Samsung A-M','Samsung','Galaxy A57','Gray','128GB','8GB','EU','on_order',31500,FALSE),
('Samsung A-M','Samsung','Galaxy A57','Navy','128GB','8GB','EU','on_order',31500,FALSE),
('Samsung A-M','Samsung','Galaxy A57','Gray','256GB','8GB','EU','on_order',33200,FALSE),
('Samsung A-M','Samsung','Galaxy A57','Icyblue','256GB','8GB','EU','in_stock',33200,FALSE),
('Samsung A-M','Samsung','Galaxy A57','Lilac','256GB','8GB','EU','in_stock',33200,FALSE),
('Samsung A-M','Samsung','Galaxy A57','Navy','256GB','8GB','EU','in_stock',33200,FALSE);
