INSERT INTO t_p31606708_tech_buying_service.catalog (category, brand, model, color, storage, region, availability, price, has_photo) VALUES
-- Apple Watch SE2 40mm
('Apple Watch','Apple','Watch SE2 2024 40mm','Midnight Sport Band (S/M)',NULL,'US','in_stock',18700,TRUE),
('Apple Watch','Apple','Watch SE2 2024 40mm','Midnight Sport Loop',NULL,'US','on_order',16600,TRUE),
('Apple Watch','Apple','Watch SE2 2024 40mm','Silver Sport Loop',NULL,'US','in_stock',19800,FALSE),
('Apple Watch','Apple','Watch SE2 2024 40mm','Starlight Sport Loop',NULL,'US','in_stock',21400,TRUE),
-- SE2 44mm
('Apple Watch','Apple','Watch SE2 2024 44mm','Midnight Sport Band (M/L)',NULL,'US','in_stock',14700,TRUE),
('Apple Watch','Apple','Watch SE2 2024 44mm','Midnight Sport Band (S/M)',NULL,'US','on_order',14800,FALSE),
('Apple Watch','Apple','Watch SE2 2024 44mm','Midnight Sport Loop',NULL,'US','on_order',15000,TRUE),
('Apple Watch','Apple','Watch SE2 2024 44mm','Silver Sport Band (M/L)',NULL,'US','in_stock',20800,TRUE),
('Apple Watch','Apple','Watch SE2 2024 44mm','Starlight Sport Loop',NULL,'US','in_stock',21400,TRUE),
-- SE3
('Apple Watch','Apple','Watch SE3 40mm','Midnight Sport Band (S/M)',NULL,'US','in_stock',20100,FALSE),
('Apple Watch','Apple','Watch SE3 40mm','Starlight Sport Band (S/M)',NULL,'US','in_stock',20800,FALSE),
('Apple Watch','Apple','Watch SE3 44mm','Midnight Sport Band (M/L)',NULL,'US','in_stock',21200,FALSE),
('Apple Watch','Apple','Watch SE3 44mm','Midnight Sport Band (S/M)',NULL,'US','on_order',22000,FALSE),
('Apple Watch','Apple','Watch SE3 44mm','Starlight Sport Band (M/L)',NULL,'US','in_stock',21900,FALSE),
('Apple Watch','Apple','Watch SE3 44mm','Starlight Sport Band (S/M)',NULL,'US','on_order',24100,FALSE),
-- S9/S10/S11
('Apple Watch','Apple','Watch S9 41mm','Midnight Sport Band (M/L)',NULL,'US','on_order',25200,FALSE),
('Apple Watch','Apple','Watch S9 41mm','Midnight Sport Band (S/M)',NULL,'US','on_order',25200,FALSE),
('Apple Watch','Apple','Watch S9 45mm','Pink Sport Band (S/M)',NULL,'US','on_order',21500,FALSE),
('Apple Watch','Apple','Watch S10 42mm','Rose Gold Sport Loop',NULL,'US','on_order',25700,FALSE),
('Apple Watch','Apple','Watch S10 46mm','Jet Black Sport Loop',NULL,'US','on_order',24600,TRUE),
('Apple Watch','Apple','Watch S10 46mm','Rose Gold Sport Band (M/L)',NULL,'US','on_order',24600,TRUE),
('Apple Watch','Apple','Watch S10 46mm','Rose Gold Sport Loop',NULL,'US','on_order',25200,FALSE),
('Apple Watch','Apple','Watch S10 46mm','Silver Sport Band (M/L)',NULL,'US','in_stock',25400,TRUE),
('Apple Watch','Apple','Watch S11 42mm','Jet Black Sport Band (S/M)',NULL,'US','on_order',26800,TRUE),
('Apple Watch','Apple','Watch S11 42mm','Jet Black Sport Band (M/L)',NULL,'US','on_order',26800,FALSE),
('Apple Watch','Apple','Watch S11 42mm','Rose Gold Sport Band (S/M)',NULL,'US','on_order',27800,TRUE),
('Apple Watch','Apple','Watch S11 42mm','Rose Gold Sport Band (M/L)',NULL,'US','on_order',28800,FALSE),
('Apple Watch','Apple','Watch S11 42mm','Space Gray Sport Band (S/M)',NULL,'US','in_stock',27600,TRUE),
('Apple Watch','Apple','Watch S11 42mm','Space Gray Sport Band (M/L)',NULL,'US','on_order',27600,FALSE),
('Apple Watch','Apple','Watch S11 42mm','Silver Sport Band (S/M)',NULL,'US','in_stock',27900,TRUE),
('Apple Watch','Apple','Watch S11 42mm','Silver Sport Band (M/L)',NULL,'US','on_order',29300,FALSE),
('Apple Watch','Apple','Watch S11 46mm','Jet Black Sport Band (M/L)',NULL,'US','in_stock',29400,TRUE),
('Apple Watch','Apple','Watch S11 46mm','Jet Black Sport Band (S/M)',NULL,'US','on_order',29400,FALSE),
('Apple Watch','Apple','Watch S11 46mm','Rose Gold Sport Band (M/L)',NULL,'US','on_order',29100,TRUE),
('Apple Watch','Apple','Watch S11 46mm','Rose Gold Sport Band (S/M)',NULL,'US','on_order',29900,FALSE),
('Apple Watch','Apple','Watch S11 46mm','Space Gray Sport Band (M/L)',NULL,'US','in_stock',28800,TRUE),
('Apple Watch','Apple','Watch S11 46mm','Silver Sport Band (M/L)',NULL,'US','in_stock',29400,TRUE),
('Apple Watch','Apple','Watch S11 42mm','Gold Ti Milanese Loop',NULL,'US','on_order',61700,FALSE),
('Apple Watch','Apple','Watch S11 42mm','Natural Ti Milanese Loop',NULL,'US','on_order',64600,FALSE),
('Apple Watch','Apple','Watch S11 42mm','Slate Ti Milanese Loop',NULL,'US','on_order',64600,FALSE),
('Apple Watch','Apple','Watch S11 46mm','Gold Ti Milanese Loop (M/L)',NULL,'US','on_order',66600,FALSE),
('Apple Watch','Apple','Watch S11 46mm','Slate Ti Milanese Loop (M/L)',NULL,'US','on_order',64600,FALSE),
('Apple Watch','Apple','Watch S11 46mm','Natural Ti Milanese Loop (M/L)',NULL,'US','on_order',66600,FALSE),
-- Ultra
('Apple Watch','Apple','Watch Ultra 2 49mm','Black Ti Dark Green Alpine Loop Medium',NULL,'US','on_order',51900,TRUE),
('Apple Watch','Apple','Watch Ultra 2 49mm','Black Ti Black Ocean Band',NULL,'US','on_order',51200,FALSE),
('Apple Watch','Apple','Watch Ultra 2 49mm','Black Ti Black Milanese Loop Small',NULL,'US','on_order',62500,FALSE),
('Apple Watch','Apple','Watch Ultra 2 49mm','Black Ti Blue Alpine Loop Large',NULL,'US','on_order',57600,FALSE),
('Apple Watch','Apple','Watch Ultra 2 49mm','Natural Ti Tan Alpine Loop Small',NULL,'US','on_order',57600,FALSE),
('Apple Watch','Apple','Watch Ultra 2 49mm','Natural Ti Tan Alpine Loop Large',NULL,'US','on_order',57600,FALSE),
('Apple Watch','Apple','Watch Ultra 2 49mm','Natural Ti Tan Alpine Loop Medium',NULL,'US','on_order',57600,FALSE),
('Apple Watch','Apple','Watch Ultra 3 49mm','Natural Ti Natural Milanese Loop Medium',NULL,'US','on_order',72900,FALSE),
('Apple Watch','Apple','Watch Ultra 3 49mm','Natural Ti Blue Alpine Loop Small',NULL,'US','on_order',62000,FALSE),
('Apple Watch','Apple','Watch Ultra 3 49mm','Black Ti Black Milanese Loop Medium',NULL,'US','on_order',73900,FALSE),
('Apple Watch','Apple','Watch Ultra 3 49mm','Black Ti Black Milanese Loop Large',NULL,'US','on_order',72600,FALSE),
('Apple Watch','Apple','Watch Ultra 3 49mm','Black Ti Blue Alpine Loop Small',NULL,'US','on_order',60700,FALSE),
('Apple Watch','Apple','Watch Ultra 3 49mm','Black Ti Black Trail Loop M/L',NULL,'US','on_order',60700,FALSE),
('Apple Watch','Apple','Watch Ultra 3 49mm','Black Ti Black Ocean Band',NULL,'US','on_order',58300,FALSE),

-- AirPods
('AirPods','Apple','EarPods Type-C',NULL,NULL,NULL,'on_order',1900,TRUE),
('AirPods','Apple','EarPods Lightning',NULL,NULL,NULL,'in_stock',1800,TRUE),
('AirPods','Apple','AirPods 4',NULL,NULL,'US','in_stock',8900,TRUE),
('AirPods','Apple','AirPods 4 ANC',NULL,NULL,'US','in_stock',12800,TRUE),
('AirPods','Apple','AirPods Pro 2 Type-C',NULL,NULL,'US','in_stock',14400,TRUE),
('AirPods','Apple','AirPods Pro 3',NULL,NULL,'US','in_stock',17900,TRUE),
('AirPods','Apple','AirPods Max 2','Midnight',NULL,'US','on_order',39900,TRUE),
('AirPods','Apple','AirPods Max 2','Starlight',NULL,'US','on_order',43300,TRUE),
('AirPods','Apple','AirPods Max 2','Purple',NULL,'US','on_order',41700,TRUE),
('AirPods','Apple','AirPods Max 2','Orange',NULL,'US','on_order',40600,TRUE),
('AirPods','Apple','AirPods Max 2','Blue',NULL,'US','on_order',42700,TRUE),
('AirPods','Apple','Apple TV','64GB',NULL,'US','in_stock',12600,TRUE),
('AirPods','Apple','Apple TV','128GB',NULL,'US','in_stock',15200,TRUE),
('AirPods','Apple','Airtag 4 Pack',NULL,NULL,NULL,'in_stock',NULL,TRUE),
('AirPods','Apple','Кабель Type-C - Type-C',NULL,NULL,NULL,'in_stock',1700,TRUE),
('AirPods','Apple','Кабель Type-C - Lightning',NULL,NULL,NULL,'in_stock',1600,TRUE);
