INSERT INTO t_p31606708_tech_buying_service.catalog (category, brand, model, color, storage, region, availability, price, has_photo) VALUES
-- Фен Dyson
('Dyson / Garmin','Dyson','Dyson HD07 (без кейса)','Blue/Copper',NULL,'EU','on_order',24100,FALSE),
('Dyson / Garmin','Dyson','Dyson HD07 (с кейсом)','Blue/Copper',NULL,'EU','on_order',29100,FALSE),
('Dyson / Garmin','Dyson','Dyson HD07 (без кейса)','Nickel/Copper',NULL,'EU','on_order',38400,FALSE),
('Dyson / Garmin','Dyson','Dyson HD08 (с кейсом)','Blue/Copper',NULL,'CN','on_order',35300,TRUE),
('Dyson / Garmin','Dyson','Dyson HD15 (без кейса)','Nickel/Copper',NULL,'EU','on_order',25200,FALSE),
('Dyson / Garmin','Dyson','Dyson HD16 (с кейсом)','Vinca Blue',NULL,'EU','on_order',28300,TRUE),
('Dyson / Garmin','Dyson','Dyson HD16 (без кейса)','Vinca Blue',NULL,'EU','on_order',46400,FALSE),
('Dyson / Garmin','Dyson','Dyson HD16 (без кейса)','Blue/Copper',NULL,'CN','on_order',31400,FALSE),
('Dyson / Garmin','Dyson','Dyson HD16 (с кейсом)','Blue/Copper',NULL,'EU','on_order',41500,FALSE),
('Dyson / Garmin','Dyson','Dyson HD16 (без кейса)','Ceramic Patina',NULL,'CN','on_order',33200,FALSE),
('Dyson / Garmin','Dyson','Dyson HD18 (без кейса)','Vinca Blue',NULL,'EU','on_order',33400,FALSE),
-- Стайлеры Dyson
('Dyson / Garmin','Dyson','Dyson HS05 (без кейса)','Nickel/Copper',NULL,NULL,'in_stock',31600,FALSE),
('Dyson / Garmin','Dyson','Dyson HS05 Long (с диффузором)','Strawberry Bronze',NULL,'EU','on_order',54000,FALSE),
('Dyson / Garmin','Dyson','Dyson HS05 Long','Nickel/Copper',NULL,'CN','on_order',39900,FALSE),
('Dyson / Garmin','Dyson','Dyson HS05 Long','Blue/Copper',NULL,'CN','on_order',39900,FALSE),
('Dyson / Garmin','Dyson','Dyson HS05 Long (с диффузором)','Blue/Copper',NULL,'EU','on_order',52900,FALSE),
('Dyson / Garmin','Dyson','Dyson HS05 Long','Fuchsia/Nickel',NULL,NULL,'in_stock',NULL,TRUE),
('Dyson / Garmin','Dyson','Dyson HS05 Long','Ceramic Pop',NULL,'CN','on_order',45800,FALSE),
('Dyson / Garmin','Dyson','Dyson HS05 Long','Ceramic Pink',NULL,'CN','on_order',50000,FALSE),
('Dyson / Garmin','Dyson','Dyson HS05 Long','Gold/Onyx',NULL,'CN','on_order',44800,FALSE),
('Dyson / Garmin','Dyson','Dyson HS08 Long','Strawberry Bronze',NULL,'CN','on_order',63600,FALSE),
('Dyson / Garmin','Dyson','Dyson HS08 Long','Vinca Blue',NULL,'CN','in_stock',31600,FALSE),
('Dyson / Garmin','Dyson','Dyson HS08 Long (с диффузором)','Vinca Blue',NULL,'EU','on_order',32700,FALSE),
('Dyson / Garmin','Dyson','Dyson HS08 Long','Jasper Plum',NULL,'CN','on_order',36300,FALSE),
('Dyson / Garmin','Dyson','Dyson HS08 Long','Blue/Copper',NULL,'CN','on_order',32700,FALSE),
('Dyson / Garmin','Dyson','Dyson HS08 Long (с диффузором)','Blue/Copper',NULL,'EU','on_order',37300,FALSE),
('Dyson / Garmin','Dyson','Dyson HS08 Long','Ceramic Patina',NULL,'EU','on_order',38400,FALSE),
('Dyson / Garmin','Dyson','Dyson HS08 Long (с диффузором)','Ceramic Patina',NULL,'EU','on_order',32400,FALSE),
('Dyson / Garmin','Dyson','Dyson HS08 Long','Red Velvet',NULL,'CN','on_order',33200,TRUE),
('Dyson / Garmin','Dyson','Dyson HS08 Long','Kanzan Pink',NULL,'CN','on_order',39900,FALSE),
('Dyson / Garmin','Dyson','Dyson HS08 Long','Amber Silk',NULL,'EU','on_order',32400,FALSE),
('Dyson / Garmin','Dyson','Dyson HS08 Long (с диффузором)','Amber Silk',NULL,'EU','on_order',32600,FALSE),
('Dyson / Garmin','Dyson','Dyson HS08 Long','Ceramic Pink',NULL,'CN','in_stock',31600,FALSE),
('Dyson / Garmin','Dyson','Dyson HS08 Long (с диффузором)','Ceramic Pink',NULL,'EU','on_order',32700,FALSE),
('Dyson / Garmin','Dyson','Dyson HS08 Long','Ceramic Apricot',NULL,'EU','on_order',40400,FALSE),
('Dyson / Garmin','Dyson','Dyson HS09 Long','Amber Silk',NULL,'EU','on_order',43300,FALSE),
('Dyson / Garmin','Dyson','Dyson HS09 Long','Jasper Plum',NULL,'CN','on_order',43300,FALSE),
('Dyson / Garmin','Dyson','Dyson HS09 Long','Ceramic Pink',NULL,'EU','on_order',43500,FALSE),
('Dyson / Garmin','Dyson','Dyson HS09 Long','Red Velvet',NULL,'CN','on_order',46400,FALSE),
('Dyson / Garmin','Dyson','Dyson HS09 Long','Ceramic Apricot',NULL,'CN','on_order',45300,FALSE),
-- Выпрямители Dyson
('Dyson / Garmin','Dyson','Dyson HT01 (с кейсом)','Jasper Plum',NULL,'CN','on_order',43300,FALSE),
('Dyson / Garmin','Dyson','Dyson HT01 (без кейса)','Ceramic Pink',NULL,'CN','on_order',29900,TRUE),
('Dyson / Garmin','Dyson','Dyson HT01 (с кейсом)','Strawberry Bronze',NULL,'CN','in_stock',31300,TRUE),
('Dyson / Garmin','Dyson','Dyson HT01 (с кейсом)','Red Velvet',NULL,'CN','in_stock',32900,FALSE),
('Dyson / Garmin','Dyson','Dyson HT01 (без кейса)','Blue/Copper',NULL,'CN','in_stock',28100,TRUE),
('Dyson / Garmin','Dyson','Dyson HT01 (без кейса)','Nickel/Copper',NULL,'CN','on_order',30400,TRUE),
('Dyson / Garmin','Dyson','Dyson HT01 (с кейсом)','Kanzan Pink',NULL,'CN','in_stock',37900,FALSE),
('Dyson / Garmin','Dyson','Dyson HT01 (с кейсом)','Amber Silk',NULL,'CN','in_stock',30600,FALSE),
('Dyson / Garmin','Dyson','Dyson HT01 (с кейсом)','Ceramic Apricot',NULL,'CN','on_order',28800,FALSE),
-- Очистители Dyson
('Dyson / Garmin','Dyson','Dyson PH05','White/Gold',NULL,'CN','on_order',66600,FALSE),
-- Пылесосы Dyson
('Dyson / Garmin','Dyson','Dyson V8 SV25 Absolute','Yellow/Nickel',NULL,'EU','on_order',38900,FALSE),
('Dyson / Garmin','Dyson','Dyson V12 SV46 Detect Slim Absolute','Yellow/Nickel',NULL,'CN','on_order',35800,FALSE),
('Dyson / Garmin','Dyson','Dyson V15 SV47 Detect Absolute','Yellow/Nickel',NULL,'CN','on_order',44800,FALSE),
('Dyson / Garmin','Dyson','Dyson V15 SV47 Detect Absolute','Gold/Gold',NULL,'EU','on_order',45900,FALSE),
('Dyson / Garmin','Dyson','Dyson V15S SV47 Detect Absolute Submarine','Yellow/Nickel',NULL,'EU','on_order',50300,FALSE),
('Dyson / Garmin','Dyson','Dyson Gen5 SV23 Detect Absolute','Nickel/Purple',NULL,'EU','on_order',49700,TRUE),
('Dyson / Garmin','Dyson','Dyson Gen5 SV23 Detect Absolute','Blue/Copper',NULL,'CN','on_order',50000,TRUE);
