ALTER TABLE t_p31606708_tech_buying_service.contracts_14d
  ADD COLUMN IF NOT EXISTS extended BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS extended_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS extended_note TEXT NULL;