-- Расширение transfer_sessions: дополнительные категории данных
ALTER TABLE t_p31606708_tech_buying_service.transfer_sessions
  ADD COLUMN IF NOT EXISTS has_notes BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS has_bookmarks BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS has_wifi BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS has_calendar BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS has_audio BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS has_messengers BOOLEAN NOT NULL DEFAULT FALSE;